apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: slippery-marsupial-go 
  janus-idp.io/tekton: slippery-marsupial-go
  backstage.io/kubernetes-id: slippery-marsupial-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: slippery-marsupial-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  